import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "/intro",
    "",
  ],

  "/demo/": [
    {
      text: "JAVA",
      icon: "mug-hot",
      prefix: "/demo/JAVA/",
      link: "",
      collapsible: true,
      expanded: false,
      children: ["java概述","基础语法","面向对象","String","Integer","Object","异常处理","IO","序列化","网络编程","泛型","反射","jdk18特性"],
    },
    {
      text: "Algorithm",
      icon: "calculator",
      prefix: "/demo/Algorithm/",
      link: "",
      collapsible: true,
      expanded: false,
      children: [
        {
          text: "贪心算法",
          icon: "lightbulb",
          prefix: "贪心算法/",
          link: "",
          collapsible: true,
          expanded: false,
          children: ["理论","分发饼干","摆动序列","最大子数组","买卖股票的最佳时机Ⅱ","跳跃游戏","跳跃游戏Ⅱ","K次取反后最大化的数组和","加油站","分发糖果","柠檬水找零"],
        },
      ],
    },
    {
      text: "Agent",
      icon: "robot",
      prefix: "/demo/Agent/",
      link: "",
      collapsible: true,
      expanded: false,
      children: ["tool","HumanInTheLoop"],
    },
    {
      text: "Tool",
      icon: "carbon:tool-kit",
      prefix: "/demo/Tool/",
      link: "",
      collapsible: true,
      expanded: false,
      children: ["git"],
    },
    {
      text: "MYSQL",
      icon: "database",
      prefix: "/demo/MYSQL/",
      link: "",
      collapsible: true,
      expanded: false,
      children: ["MYSQL基础","数据库架构","存储引擎","日志","SQL优化","索引","锁","事务","高并发","运维"],
    },
    {
      text: "Redis",
      icon: "simple-icons:redis",
      prefix: "/demo/redis/",
      link: "",
      collapsible: true,
      expanded: false,
      children: ["介绍","持久化","高可用"],
    },
    {
      text: "llm",
      icon: "brain",
      prefix: "/demo/llm/",
      link: "",
      collapsible: true,
      expanded: false,
      children: ["机器学习","pytorch"],
    },
    // "/intro",
  ],

  "/project/": [
    {
      text: "26'ICAUS",
      icon: "tower-broadcast",
      prefix: "/project/26'ICAUS/",
      link: "",
      collapsible: true,
      expanded: false,
      children: ["介绍"],
    },
    {
      text: "pytorch",
      icon: "fire",
      prefix: "/project/pytorch/",
      link: "",
      collapsible: true,
      expanded: false,
      children: ["Tensor"],
    },
    {
      text: "AgriBrain",
      icon: "seedling",
      prefix: "/project/AgriBrain/",
      link: "",
      collapsible: true,
      expanded: false,
      children: ["项目介绍","Memory"],
    },
  ],
});
